"""empty message

Revision ID: 44d30823a996
Revises: 6e1f9b20f11b
Create Date: 2023-01-19 14:57:50.440373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44d30823a996'
down_revision = '6e1f9b20f11b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=10), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section')
    )
    op.drop_table('assignments_due')
    with op.batch_alter_table('due_dates', schema=None) as batch_op:
        batch_op.alter_column('section',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_foreign_key('duedatesection', 'sections', ['section'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('section',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_foreign_key('usersection', 'sections', ['section'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('section',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    with op.batch_alter_table('due_dates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('section',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    op.create_table('assignments_due',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('assignment', sa.INTEGER(), nullable=True),
    sa.Column('section', sa.VARCHAR(length=10), nullable=True),
    sa.Column('duedate', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['assignment'], ['assignments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sections')
    # ### end Alembic commands ###
