"""empty message

Revision ID: 8381ceb3431a
Revises: 109b0a15e729
Create Date: 2023-02-26 11:05:27.368476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8381ceb3431a'
down_revision = '109b0a15e729'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('User',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('email', sa.String(length=50), nullable=True),
    # sa.Column('password', sa.String(length=50), nullable=True),
    # sa.Column('first_name', sa.String(length=50), nullable=True),
    # sa.Column('last_name', sa.String(length=50), nullable=True),
    # sa.Column('student_id', sa.String(length=10), nullable=True),
    # sa.Column('section', sa.Integer(), nullable=True),
    # sa.Column('role', sa.String(length=10), nullable=True),
    # sa.ForeignKeyConstraint(['section'], ['sections.id'], ),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('email'),
    # sa.UniqueConstraint('student_id')
    # )
    # op.drop_table('user')
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_column('grade')

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), nullable=True),
    sa.Column('password', sa.VARCHAR(length=50), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('student_id', sa.VARCHAR(length=10), nullable=True),
    sa.Column('role', sa.VARCHAR(length=10), nullable=True),
    sa.Column('section', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['section'], ['sections.id'], name='usersection'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('student_id')
    )
    op.drop_table('User')
    # ### end Alembic commands ###
