"""empty message

Revision ID: 109b0a15e729
Revises: 8337475d9e1c
Create Date: 2023-02-24 13:00:40.021804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '109b0a15e729'
down_revision = '8337475d9e1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('User',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('email', sa.String(length=50), nullable=True),
    # sa.Column('password', sa.String(length=50), nullable=True),
    # sa.Column('first_name', sa.String(length=50), nullable=True),
    # sa.Column('last_name', sa.String(length=50), nullable=True),
    # sa.Column('student_id', sa.String(length=10), nullable=True),
    # sa.Column('section', sa.Integer(), nullable=True),
    # sa.Column('role', sa.String(length=10), nullable=True),
    # sa.ForeignKeyConstraint(['section'], ['sections.id'], ),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('email'),
    # sa.UniqueConstraint('student_id')
    # )
    # op.drop_table('user')
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct_answer', sa.Boolean(), nullable=True))
        batch_op.drop_column('corrrect_answer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('corrrect_answer', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('correct_answer')

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), nullable=True),
    sa.Column('password', sa.VARCHAR(length=50), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('student_id', sa.VARCHAR(length=10), nullable=True),
    sa.Column('role', sa.VARCHAR(length=10), nullable=True),
    sa.Column('section', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['section'], ['sections.id'], name='usersection'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('student_id')
    )
    op.drop_table('User')
    # ### end Alembic commands ###
