"""empty message

Revision ID: 569e00f5fe5e
Revises: 7d50cfce229c
Create Date: 2023-11-10 07:31:03.884551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '569e00f5fe5e'
down_revision = '7d50cfce229c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_bank',
    sa.Column('question_id', sa.String(length=10), nullable=False),
    sa.Column('topic', sa.String(length=50), nullable=True),
    sa.Column('question', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('answer_bank',
    sa.Column('question_id', sa.String(length=10), nullable=False),
    sa.Column('answer_id', sa.String(length=10), nullable=False),
    sa.Column('answer_txt', sa.String(length=100), nullable=True),
    sa.Column('correct_answer', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.PrimaryKeyConstraint('question_id', 'answer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer_bank')
    op.drop_table('question_bank')
    # ### end Alembic commands ###
