"""empty message

Revision ID: 6e1f9b20f11b
Revises: 9c5d794ca881
Create Date: 2023-01-18 18:37:11.066757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e1f9b20f11b'
down_revision = '9c5d794ca881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments_due',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=10), nullable=True),
    sa.Column('duedate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignment'], ['assignments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignments_due')
    # ### end Alembic commands ###
