"""empty message

Revision ID: 884b7b7315b0
Revises: 9a0f2636f860
Create Date: 2024-01-17 15:41:59.679670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884b7b7315b0'
down_revision = '9a0f2636f860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    # ### end Alembic commands ###
