"""empty message

Revision ID: 9c5d794ca881
Revises: ce0d2b7e6124
Create Date: 2023-01-18 14:51:24.910609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c5d794ca881'
down_revision = 'ce0d2b7e6124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('due_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=10), nullable=True),
    sa.Column('duedate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignment'], ['assignments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_column('due')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due', sa.DATETIME(), nullable=True))

    op.drop_table('due_dates')
    # ### end Alembic commands ###
