"""empty message

Revision ID: a5f09300f066
Revises: 569e00f5fe5e
Create Date: 2024-01-06 10:21:51.009791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f09300f066'
down_revision = '569e00f5fe5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answers')
    op.drop_table('questions')
    op.drop_table('question_bank')
    op.drop_table('quizzes')
    op.drop_table('answer_bank')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_bank',
    sa.Column('question_id', sa.VARCHAR(length=10), nullable=False),
    sa.Column('answer_id', sa.VARCHAR(length=10), nullable=False),
    sa.Column('answer_txt', sa.VARCHAR(length=100), nullable=True),
    sa.Column('correct_answer', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.PrimaryKeyConstraint('question_id', 'answer_id')
    )
    op.create_table('quizzes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('quiz_header', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('submitted', sa.BOOLEAN(), nullable=True),
    sa.Column('grade', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_header'], ['quiz_header.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_bank',
    sa.Column('question_id', sa.VARCHAR(length=10), nullable=False),
    sa.Column('topic', sa.VARCHAR(length=50), nullable=True),
    sa.Column('question', sa.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('questions',
    sa.Column('quiz_id', sa.INTEGER(), nullable=False),
    sa.Column('question_id', sa.VARCHAR(length=10), nullable=False),
    sa.Column('topic', sa.VARCHAR(length=50), nullable=True),
    sa.Column('question', sa.VARCHAR(length=500), nullable=True),
    sa.Column('display_order', sa.INTEGER(), nullable=True),
    sa.Column('answer_chosen', sa.VARCHAR(length=20), nullable=True),
    sa.Column('is_correct', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('quiz_id', 'question_id')
    )
    op.create_table('answers',
    sa.Column('quiz_id', sa.INTEGER(), nullable=False),
    sa.Column('question_id', sa.VARCHAR(length=10), nullable=False),
    sa.Column('answer_id', sa.VARCHAR(length=10), nullable=False),
    sa.Column('display_order', sa.INTEGER(), nullable=True),
    sa.Column('answer_txt', sa.VARCHAR(length=100), nullable=True),
    sa.Column('correct_answer', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('quiz_id', 'question_id', 'answer_id')
    )
    # ### end Alembic commands ###
