"""empty message

Revision ID: a9ca7b3f0f6e
Revises: d2fae7edd236
Create Date: 2022-12-31 15:56:38.607276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9ca7b3f0f6e'
down_revision = 'd2fae7edd236'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('assignment', sa.Integer(), nullable=True),
    sa.Column('submission', sa.String(length=50), nullable=True),
    sa.Column('date_submitted', sa.DateTime(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submissions')
    # ### end Alembic commands ###
