"""empty message

Revision ID: c580f7e1b3ba
Revises: d872a5bfa9ab
Create Date: 2023-10-23 09:40:34.377203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c580f7e1b3ba'
down_revision = 'd872a5bfa9ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade_category', sa.String(length=50), nullable=True))

    with op.batch_alter_table('quiz_header', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade_category', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_header', schema=None) as batch_op:
        batch_op.drop_column('grade_category')

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_column('grade_category')

    # ### end Alembic commands ###
