"""empty message

Revision ID: c8cf8d1df515
Revises: a9ca7b3f0f6e
Create Date: 2023-01-07 18:56:11.729266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8cf8d1df515'
down_revision = 'a9ca7b3f0f6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.create_foreign_key('assignmentk', 'assignments', ['assignment'], ['id'])

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_foreign_key('assignmentk2', 'assignments', ['assignment'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_constraint('assignmentk2', type_='foreignkey')

    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_constraint('assignmentk', type_='foreignkey')

    # ### end Alembic commands ###
