"""empty message

Revision ID: d872a5bfa9ab
Revises: 
Create Date: 2023-10-13 09:41:16.308267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd872a5bfa9ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retries', sa.Integer(), nullable=True))

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('submission',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('submission',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_column('retries')

    # ### end Alembic commands ###
